### ISSUE TITLE
Unknown attribute "maxsize"

### ISSUE THREAD

**Issue by nextpulse** [BrunoSalerno/overpass-api-ruby#4]
Recent changes causing error:

Unknown attribute "maxsize" in element "osm-script"

**Comment by nextpulse** [comment]
The bug is due to diff attribute limit name for XML vs QL:

http://wiki.openstreetmap.org/wiki/Overpass_API/Language_Guide#Resource_management_options_.28osm-script.29

Fix is needed in https://github.com/BrunoSalerno/overpass-api-ruby/blob/master/lib/xml.rb
element-limit (instead of maxsize)

**Comment by BrunoSalerno** [comment]
@nextpulse thanks for the report! It's fixed ;)
